### ISSUE TITLE
Unbannable

### ISSUE THREAD

**Issue by MechRalph04** [PocketEssential/RequestPlugins#11]
So hello PocketEssential. I'd like to have a command that a player won't be banned even the IP. So I'm thinking is by editing config.yml or any ".yml" file and adding a player in the yml file. And when a hacker or a traitor tried to ban the player added in the unbannable won't be banned. Hope you liked the request! :D

**Comment by ghost** [comment]
@MechRalph04 Noted, this plugin will be made soon expect it to be cool :wink:

**Comment by ghost** [comment]
This is completed!! https://github.com/PocketEssential/Unbanable

**Comment by MechRalph04** [comment]
@AnkitM252 Yay! This is epic!
