### ISSUE TITLE
BossBar Random Messages

### ISSUE THREAD

**Issue by starterdragon** [PocketEssential/RequestPlugins#4]
Please make a boss bar name changes to random messages with preset amount of time which is configurable on config..

And please make it global (doesn't need to spawn a wither / it only appears when near a wither)

THANKS!!

**Comment by xZeroMCPE** [comment]
Nice, we're working on it :)

**Comment by xZeroMCPE** [comment]
Completed!

"https://github.com/PocketEssential/BossBarAPI"
