### ISSUE TITLE
Rank Selector

### ISSUE THREAD

**Issue by starterdragon** [PocketEssential/RequestPlugins#6]
Hello again!

Do u know the language selector (sign with buttons on sides) from big server (ex LifeBoat) ?
I have this idea but instead of changing a language, it will change the player's rank instead..

First I think getting PurePerm's group.yml is a good idea but later on I think that they might select OP group, so, It'll be a better idea if this creates own config, but ofc ranks should be same with what in PP.

to add more twist, you can add permission for vip so when they select it, a message will be sent if they dont have perm.. so on comment is my example config look, but u can change it if you want:

**Comment by starterdragon** [comment]
SAMPLE CONFIG // YOU CAN ADD ECONOMY SUPPORT IF YOU WANT ;)
Guest:
  is_vip: false
  price: 0
Builder:
  is_vip: true
  price: 9999999
Loyal:
  is_vip: false
  price: 0
Fan:
  is_vip: false
  price: 1

PS. I just don't have the plugin src and I really have no idea how and what to start,,

**Comment by xZeroMCPE** [comment]
Confused, mind telling me more in a detailed way as possible.

**Comment by starterdragon** [comment]
![image](https://cloud.githubusercontent.com/assets/16812043/20457926/b030ee40-aed1-11e6-9d39-f85b86ede41b.png)
This, imagine a the three buttons are (in order from left to right) previous, select, next..

when you press next, the next rank on config appears, same with previous.
and when you press select(middle) the current group(@ranks) on sign will be set to you..

**Comment by xZeroMCPE** [comment]
Ah okay i got it...

You press the next button, it displays the next rank on the sign? the buttom button sets the rank on you right?

**Comment by starterdragon** [comment]
I think this may need two configs, (for example) selector.yml and groups.yml
in selector, it is where the signs are saved..
this will be the structure:

sign
-X
-Y
-Z
-prevB
--x
--y
--z
-selectB
--x
--y
--z
-nextB
--x
--y
--z

sorry to bother, but If I only know where to begin I would not bother anyone :laughing:

**Comment by xZeroMCPE** [comment]
Alright, got it. 

So support for Economy's ? 

Like user have to pay to get the ranks? or...

**Comment by starterdragon** [comment]
It would be awesome, but it's up to you as always.

**Comment by xZeroMCPE** [comment]
Okay, so they can choose any rank they want?

**Comment by starterdragon** [comment]
Yep..

**Comment by xZeroMCPE** [comment]
Okay, got it

**Comment by starterdragon** [comment]
Ohh.. Thanks! I knew you guys are the only one that can help.. ;)
